services:
  - type: web
    name: mission-api
    runtime: python
    rootDir: mission_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

  - type: web
    name: benefit-api
    runtime: python
    rootDir: benefit_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
